In [2]:
import numpy as np

## 1.Calculating Total Revenue

In [2]:
prices =  np.array([9.99, 19.99, 29.99, 24.99, 35.99])
prices

array([ 9.99, 19.99, 29.99, 24.99, 35.99])

In [3]:
quantities = np.array([12,34,45,5,67])
quantities

array([12, 34, 45,  5, 67])

In [4]:
revenue_per_product = prices * quantities
revenue_per_product

array([ 119.88,  679.66, 1349.55,  124.95, 2411.33])

In [5]:
total_revenue = np.sum(revenue_per_product)
total_revenue

4685.37

## 2. Analyzing Blog Post Stats

In [8]:
views = np.array([1000, 700, 300, 500, 300, 1100])
views

array([1000,  700,  300,  500,  300, 1100])

In [10]:
max_views = np.max(views) # analog si cu metoda 'min()'
max_views

1100

In [11]:
min_views = np.min(views) 
min_views

300

In [12]:
average_views = np.mean(views) 
average_views

650.0

## 3. Splitting Order into Batches

In [13]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])

In [14]:
batches = np.split(order_ids, 3)
batches

[array([1001, 1002, 1003]),
 array([1004, 1005, 1006]),
 array([1007, 1008, 1009])]

In [15]:
for batch in batches:
    print (batch)

[1001 1002 1003]
[1004 1005 1006]
[1007 1008 1009]


In [16]:
for batch in batches:
    print (batch[0])

1001
1004
1007


In [20]:
for i, batch in enumerate(batches):
    print (f"Batch number {i}:")
    print ("Primul element din lot:     ", batch[0])
    print ("Al Doilea element din lot:  ", batch[1])
    print ("Al treilea element din lot: ", batch[2])
    print ('') # adugam un rind nou

Batch number 0:
Primul element din lot:      1001
Al Doilea element din lot:   1002
Al treilea element din lot:  1003

Batch number 1:
Primul element din lot:      1004
Al Doilea element din lot:   1005
Al treilea element din lot:  1006

Batch number 2:
Primul element din lot:      1007
Al Doilea element din lot:   1008
Al treilea element din lot:  1009



## 4. Categorizing Product Ratings

In [21]:
ratings = np.array([1.2, 4.3, 2.4, 6.4, 7.5, 8.3, 2.5, 4.7])
ratings

array([1.2, 4.3, 2.4, 6.4, 7.5, 8.3, 2.5, 4.7])

In [24]:
# Aflam reitingurile pozitive si begative
positive_ratings = ratings[ratings >=4.0]
positive_ratings

array([4.3, 6.4, 7.5, 8.3, 4.7])

In [25]:
negative_ratings = ratings[ratings <4.0]
negative_ratings

array([1.2, 2.4, 2.5])

## 5. Calculate Total and Average quantities sold

In [31]:
# avem 4 producte si 2 comenzi
order_quantities = np.array([[3, 5, 2, 7], [8, 9, 3, 1]])
order_quantities

array([[3, 5, 2, 7],
       [8, 9, 3, 1]])

In [33]:
total_quantities_sold = np.sum(order_quantities)
total_quantities_sold
# In total produse vindute

38

In [34]:
# Cantitatea totala pe product vindut 
total_quantities_sold = np.sum(order_quantities, axis=0)
# adunam dupa 'axa 0'
total_quantities_sold
# in total in 2 comenzi produs 1= 11, produs 2= 14,produs 2= 5,produs 2= 8 

array([11, 14,  5,  8])

In [36]:
# Cantitatea totala de producte vindute in 2 comenzi
total_quantities_sold_per_order = np.sum(order_quantities, axis=1)
# adunam dupa 'axa 1'
total_quantities_sold_per_order
# in 1 comanda 17 produse, in 2 comanda 21 produse

array([17, 21])

In [37]:
average_quantities_sold = np.mean(order_quantities, axis=0)
average_quantities_sold
# aflam media produselor vindute in cele 2 comenzi

array([5.5, 7. , 2.5, 4. ])

## 6. Calculate Average product Rating and Maximum rating per Category

In [3]:
# Fiecare rind asta este un produs; Avem 3 produse
# Fiecare coloane este raiting pe 4 categorii
products_ratings = np.array([
    [4.3, 3.3, 3.2, 5.0],
    [4.2, 3.1, 4.8, 0.8],
    [3.7, 2.1, 2.9, 0.5]
])
products_ratings

array([[4.3, 3.3, 3.2, 5. ],
       [4.2, 3.1, 4.8, 0.8],
       [3.7, 2.1, 2.9, 0.5]])

In [9]:
# Media produselor pentru fiecare categorie
avergae_rating_per_category = np.round(np.mean(products_ratings, axis=0),2)
avergae_rating_per_category

array([4.07, 2.83, 3.63, 2.1 ])

In [13]:
# Maximum produselor pentru fiecare categorie
max_rating_per_category = np.max(products_ratings, axis=0)
max_rating_per_category

array([4.3, 3.3, 4.8, 5. ])

In [11]:
# Media pentru fiecare product 
avergae_rating_per_product = np.round(np.mean(products_ratings, axis=1),2)
avergae_rating_per_product

array([3.95, 3.23, 2.3 ])

In [14]:
# Minimum pentru fiecare product 
min_rating_per_product = np.mean(products_ratings, axis=1)
min_rating_per_product

array([3.95 , 3.225, 2.3  ])

## 7. Generation of the sample stock data

In [27]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April','Tue 2 May']
price_types = ['Open', 'Close', 'High', 'Low']

In [28]:
#Creem masivul (3, 2, 4) cu preturi generate random
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies),len(days),len(price_types))),3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [22]:
# ne uitam ce forma are masivul
stock_prices.shape 

(3, 2, 4)

In [29]:
# Prcurgem tot masivul tridiminseunal cu iteratsiile 'for in'
for index_axis_0, company in enumerate(companies):
    print(f"Stock prices for the {company}:")
    for index_axis_1, day in enumerate(days):
        print(f"Day: {day}")
        for index_axis_2, price_type in enumerate(price_types):
            print(f"{price_type} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}")
        print('')
    print('')

Stock prices for the Google:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tue 2 May
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft:
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tue 2 May
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tue 2 May
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692


