In [2]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
# a 3 valoare este pasul '3'
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [6]:
np.arange(-10,30,5)

array([-10,  -5,   0,   5,  10,  15,  20,  25])

In [8]:
# Versia cu argumentele cu nume
np.arange(start=-10, stop=30, step=5)

array([-10,  -5,   0,   5,  10,  15,  20,  25])

In [10]:
np.arange(20).reshape([2,10])
# Primim un masiv de 2 dimensiuni 2 rinduri si 10 colonitse (2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [11]:
np.arange(20).reshape([2,2,5])
# Primi masiv cu 3 dimansiuni

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [12]:
np.arange(20).reshape([4,5])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
np.arange(20).reshape([4,5]).reshape([2,2,5])
# Oricind putem sa schimbam reformam masivul

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [14]:
np.random.random((10,))

array([0.30448643, 0.23351528, 0.87944058, 0.89614012, 0.06005736,
       0.87533614, 0.47878874, 0.84478935, 0.99237425, 0.40444582])

In [16]:
np.random.random((10,)).reshape([2,5])
# primi deja un masiv bidiminseional

array([[0.53772368, 0.95943914, 0.15977449, 0.0708048 , 0.87452986],
       [0.92610829, 0.8263344 , 0.96492924, 0.37910967, 0.3047185 ]])

In [18]:
np.random.random((10,)).reshape((2,5))
# se poate de indicat si cortedsj () 

array([[0.12603866, 0.04841405, 0.39539295, 0.01258584, 0.82868999],
       [0.58293721, 0.97445756, 0.99625974, 0.56043567, 0.34934487]])

In [3]:
np.random.seed(10)
np.random.randint(50, 80, (4,3,3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75]],

       [[79, 66, 79],
        [67, 76, 58],
        [59, 50, 60]],

       [[58, 72, 54],
        [69, 66, 54],
        [65, 61, 72]],

       [[74, 61, 76],
        [51, 58, 54],
        [64, 67, 69]]])

In [5]:
np.random.seed(10)
np.random.randint(50, 80, (4,3,3)).flatten()
# 'flatten' transforma in array unidiminsional

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54, 65, 61, 72, 74, 61, 76, 51, 58, 54, 64,
       67, 69])

In [7]:
np.arange(30).reshape((3,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])