In [1]:
import numpy as np

In [6]:
first = np.array([[1,2,3,4],[5,6,7,8]])
first

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
first.shape

(2, 4)

In [5]:
first.ndim

2

In [7]:
second = np.array([[9,10,11,12],[13,14,15,16]])
second

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
second.shape

(2, 4)

In [9]:
first + second

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [10]:
first + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [11]:
first - 1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
first * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [13]:
first / 3

array([[0.33333333, 0.66666667, 1.        , 1.33333333],
       [1.66666667, 2.        , 2.33333333, 2.66666667]])

In [14]:
first

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
first[1,1]

6

In [16]:
first[0,1]

2

In [17]:
first[0,3]

4

In [18]:
first[1,3]

8

In [20]:
np.concatenate((first, second))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
np.concatenate((second, first))

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [23]:
np.concatenate((first, second), axis=1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [25]:
np.concatenate((np.array([1,2,3,4]), np.array([5,6,7,8])))

array([1, 2, 3, 4, 5, 6, 7, 8])